// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: hackathon25

#ifndef _HACKATHON25_UI_H
#define _HACKATHON25_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_HomeScreeen
void ui_HomeScreeen_screen_init(void);
extern lv_obj_t * ui_HomeScreeen;
void ui_event_ParkButton(lv_event_t * e);
extern lv_obj_t * ui_ParkButton;
extern lv_obj_t * ui_Image1;
void ui_event_WiFiButton(lv_event_t * e);
extern lv_obj_t * ui_WiFiButton;
extern lv_obj_t * ui_Image2;
void ui_event_SettingsButton(lv_event_t * e);
extern lv_obj_t * ui_SettingsButton;
extern lv_obj_t * ui_Image3;
void ui_event_MusicButton(lv_event_t * e);
extern lv_obj_t * ui_MusicButton;
extern lv_obj_t * ui_Image4;
void ui_event_DrivingInfo(lv_event_t * e);
extern lv_obj_t * ui_DrivingInfo;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_TimeLabel;
extern lv_obj_t * ui_DateLabel;
extern lv_obj_t * ui_TempLabel;
extern lv_obj_t * ui_HumidityLabel;
void ui_event_Maps(lv_event_t * e);
extern lv_obj_t * ui_Maps;
extern lv_obj_t * ui_Image6;
// SCREEN: ui_ParkMode
void ui_ParkMode_screen_init(void);
extern lv_obj_t * ui_ParkMode;
void ui_event_Homepark(lv_event_t * e);
extern lv_obj_t * ui_Homepark;
extern lv_obj_t * ui_HomeParkLabel;
extern lv_obj_t * ui_ReverseCam;
// SCREEN: ui_Settings
void ui_Settings_screen_init(void);
extern lv_obj_t * ui_Settings;
void ui_event_SaveButton(lv_event_t * e);
extern lv_obj_t * ui_SaveButton;
extern lv_obj_t * ui_SaveButtonLabel;
extern lv_obj_t * ui_SettingsNaslov;
extern lv_obj_t * ui_SliderSound;
extern lv_obj_t * ui_SliderLight;
extern lv_obj_t * ui_SoundLabel;
extern lv_obj_t * ui_LightLabel;
void ui_event_Left_Signalization(lv_event_t * e);
extern lv_obj_t * ui_Left_Signalization;
extern lv_obj_t * ui_LeftSignalizationLabel;
void ui_event_Right_signalization(lv_event_t * e);
extern lv_obj_t * ui_Right_signalization;
extern lv_obj_t * ui_RightSignalizationLabel;
void ui_event_LightsButton(lv_event_t * e);
extern lv_obj_t * ui_LightsButton;
extern lv_obj_t * ui_LeftSignalizationLabel1;
// SCREEN: ui_CarInfo
void ui_CarInfo_screen_init(void);
extern lv_obj_t * ui_CarInfo;
extern lv_obj_t * ui_Speed;
extern lv_obj_t * ui_Distance_;
extern lv_obj_t * ui_SpeedPlaceholder;
extern lv_obj_t * ui_Tilt;
extern lv_obj_t * ui_Incline;
extern lv_obj_t * ui_TiltNum;
extern lv_obj_t * ui_InclineNum;
void ui_event_CarInfoBackButton(lv_event_t * e);
extern lv_obj_t * ui_CarInfoBackButton;
extern lv_obj_t * ui_InfoBackLabel;
extern lv_obj_t * ui_SpeedLabel;
extern lv_obj_t * ui_Distance_Label;
// SCREEN: ui_MapScreen
void ui_MapScreen_screen_init(void);
extern lv_obj_t * ui_MapScreen;
extern lv_obj_t * ui_Image7;
void ui_event_HomeMaps(lv_event_t * e);
extern lv_obj_t * ui_HomeMaps;
extern lv_obj_t * ui_InfoBackLabelMaps;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_730112842);    // assets\letter-p_5584659 (1).png
LV_IMG_DECLARE(ui_img_1548857385);    // assets\wifi_5915249 (1).png
LV_IMG_DECLARE(ui_img_1896724463);    // assets\setting_7518375 (1).png
LV_IMG_DECLARE(ui_img_1924809568);    // assets\itunes_1384045 (1).png
LV_IMG_DECLARE(ui_img_1600593050);    // assets\car-parking_3555291 (1).png
LV_IMG_DECLARE(ui_img_2008805362);    // assets\location_15917865 (1).png
LV_IMG_DECLARE(ui_img_1599370223);    // assets\reverse_park (1).png
LV_IMG_DECLARE(ui_img_maps_1_png);    // assets\maps_1.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
