// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: hackathon25

#include "ui.h"

void MusicEventCallback(lv_event_t * e)
{
	// Your code here
}

void WiFiProvEvent(lv_event_t * e)
{
	// Your code here
}
