// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: hackathon25

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void ParkButtonCb(lv_event_t * e);
void WifiConnectCb(lv_event_t * e);
void WifiProvisionCb(lv_event_t * e);
void MusicButtonCb(lv_event_t * e);
void HomeParkCb(lv_event_t * e);
void SaveButtonCb(lv_event_t * e);
void LeftSignalCb(lv_event_t * e);
void RightSignalCb(lv_event_t * e);
void autoLightsCb(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
