// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: hackathon25

#include "../ui.h"

void ui_MapScreen_screen_init(void)
{
    ui_MapScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MapScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image7 = lv_img_create(ui_MapScreen);
    lv_img_set_src(ui_Image7, &ui_img_maps_1_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image7, 700);

    ui_HomeMaps = lv_btn_create(ui_MapScreen);
    lv_obj_set_width(ui_HomeMaps, 60);
    lv_obj_set_height(ui_HomeMaps, 50);
    lv_obj_set_x(ui_HomeMaps, -115);
    lv_obj_set_y(ui_HomeMaps, -74);
    lv_obj_set_align(ui_HomeMaps, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeMaps, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HomeMaps, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HomeMaps, lv_color_hex(0x5275A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeMaps, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_InfoBackLabelMaps = lv_label_create(ui_HomeMaps);
    lv_obj_set_width(ui_InfoBackLabelMaps, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_InfoBackLabelMaps, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_InfoBackLabelMaps, LV_ALIGN_CENTER);
    lv_label_set_text(ui_InfoBackLabelMaps, "Home");

    lv_obj_add_event_cb(ui_HomeMaps, ui_event_HomeMaps, LV_EVENT_ALL, NULL);

}
