// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: hackathon25

#include "../ui.h"

void ui_Settings_screen_init(void)
{
    ui_Settings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Settings, lv_color_hex(0xA6BDD2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Settings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Settings, lv_color_hex(0x9BA0D0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Settings, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SaveButton = lv_btn_create(ui_Settings);
    lv_obj_set_width(ui_SaveButton, 200);
    lv_obj_set_height(ui_SaveButton, 35);
    lv_obj_set_x(ui_SaveButton, 42);
    lv_obj_set_y(ui_SaveButton, 88);
    lv_obj_set_align(ui_SaveButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SaveButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SaveButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SaveButton, lv_color_hex(0x5275A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SaveButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SaveButtonLabel = lv_label_create(ui_SaveButton);
    lv_obj_set_width(ui_SaveButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SaveButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SaveButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SaveButtonLabel, "Save and Exit");

    ui_SettingsNaslov = lv_label_create(ui_Settings);
    lv_obj_set_width(ui_SettingsNaslov, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingsNaslov, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SettingsNaslov, 0);
    lv_obj_set_y(ui_SettingsNaslov, -82);
    lv_obj_set_align(ui_SettingsNaslov, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingsNaslov, "Settings");
    lv_obj_set_style_text_color(ui_SettingsNaslov, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SettingsNaslov, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SettingsNaslov, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderSound = lv_slider_create(ui_Settings);
    lv_obj_set_width(ui_SliderSound, 160);
    lv_obj_set_height(ui_SliderSound, 10);
    lv_obj_set_x(ui_SliderSound, 30);
    lv_obj_set_y(ui_SliderSound, 2);
    lv_obj_set_align(ui_SliderSound, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_SliderSound, lv_color_hex(0x5275A1), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderSound, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_SliderLight = lv_slider_create(ui_Settings);
    lv_obj_set_width(ui_SliderLight, 160);
    lv_obj_set_height(ui_SliderLight, 10);
    lv_obj_set_x(ui_SliderLight, 30);
    lv_obj_set_y(ui_SliderLight, 34);
    lv_obj_set_align(ui_SliderLight, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_SliderLight, lv_color_hex(0x5275A1), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderLight, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_SoundLabel = lv_label_create(ui_Settings);
    lv_obj_set_width(ui_SoundLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SoundLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SoundLabel, -112);
    lv_obj_set_y(ui_SoundLabel, 3);
    lv_obj_set_align(ui_SoundLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SoundLabel, "Sound");
    lv_obj_set_style_text_color(ui_SoundLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SoundLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LightLabel = lv_label_create(ui_Settings);
    lv_obj_set_width(ui_LightLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LightLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LightLabel, -112);
    lv_obj_set_y(ui_LightLabel, 36);
    lv_obj_set_align(ui_LightLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LightLabel, "Light");
    lv_obj_set_style_text_color(ui_LightLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LightLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Left_Signalization = lv_btn_create(ui_Settings);
    lv_obj_set_width(ui_Left_Signalization, 64);
    lv_obj_set_height(ui_Left_Signalization, 38);
    lv_obj_set_x(ui_Left_Signalization, -73);
    lv_obj_set_y(ui_Left_Signalization, -39);
    lv_obj_set_align(ui_Left_Signalization, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Left_Signalization, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Left_Signalization, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Left_Signalization, lv_color_hex(0x5275A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Left_Signalization, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LeftSignalizationLabel = lv_label_create(ui_Left_Signalization);
    lv_obj_set_width(ui_LeftSignalizationLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LeftSignalizationLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LeftSignalizationLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LeftSignalizationLabel, "< --");

    ui_Right_signalization = lv_btn_create(ui_Settings);
    lv_obj_set_width(ui_Right_signalization, 64);
    lv_obj_set_height(ui_Right_signalization, 38);
    lv_obj_set_x(ui_Right_signalization, 81);
    lv_obj_set_y(ui_Right_signalization, -39);
    lv_obj_set_align(ui_Right_signalization, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Right_signalization, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Right_signalization, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Right_signalization, lv_color_hex(0x5275A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Right_signalization, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RightSignalizationLabel = lv_label_create(ui_Right_signalization);
    lv_obj_set_width(ui_RightSignalizationLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RightSignalizationLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RightSignalizationLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RightSignalizationLabel, "-- >");

    ui_LightsButton = lv_btn_create(ui_Settings);
    lv_obj_set_width(ui_LightsButton, 64);
    lv_obj_set_height(ui_LightsButton, 38);
    lv_obj_set_x(ui_LightsButton, 3);
    lv_obj_set_y(ui_LightsButton, -39);
    lv_obj_set_align(ui_LightsButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LightsButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_LightsButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LightsButton, lv_color_hex(0x5275A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LightsButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LeftSignalizationLabel1 = lv_label_create(ui_LightsButton);
    lv_obj_set_width(ui_LeftSignalizationLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LeftSignalizationLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LeftSignalizationLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LeftSignalizationLabel1, "Auto");

    lv_obj_add_event_cb(ui_SaveButton, ui_event_SaveButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Left_Signalization, ui_event_Left_Signalization, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Right_signalization, ui_event_Right_signalization, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LightsButton, ui_event_LightsButton, LV_EVENT_ALL, NULL);

}
