// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: hackathon25

#include "../ui.h"

void ui_Settings_screen_init(void)
{
    ui_Settings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Settings, lv_color_hex(0x77A7A0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Settings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Save = lv_btn_create(ui_Settings);
    lv_obj_set_width(ui_Save, 200);
    lv_obj_set_height(ui_Save, 35);
    lv_obj_set_x(ui_Save, 42);
    lv_obj_set_y(ui_Save, 88);
    lv_obj_set_align(ui_Save, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Save, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Save, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Save, lv_color_hex(0x5275A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Save, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Save);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Save and Exit");

    ui_SettingsNaslov = lv_label_create(ui_Settings);
    lv_obj_set_width(ui_SettingsNaslov, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingsNaslov, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SettingsNaslov, 0);
    lv_obj_set_y(ui_SettingsNaslov, -104);
    lv_obj_set_align(ui_SettingsNaslov, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingsNaslov, "Settings");
    lv_obj_set_style_text_color(ui_SettingsNaslov, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SettingsNaslov, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_SettingsNaslov, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SettingsNaslov, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFiConnectButton = lv_btn_create(ui_Settings);
    lv_obj_set_width(ui_WiFiConnectButton, 183);
    lv_obj_set_height(ui_WiFiConnectButton, 29);
    lv_obj_set_x(ui_WiFiConnectButton, -46);
    lv_obj_set_y(ui_WiFiConnectButton, -28);
    lv_obj_set_align(ui_WiFiConnectButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WiFiConnectButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WiFiConnectButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WiFi_Connect = lv_label_create(ui_WiFiConnectButton);
    lv_obj_set_width(ui_WiFi_Connect, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WiFi_Connect, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WiFi_Connect, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WiFi_Connect, "WiFi Connect");
    lv_obj_set_style_text_color(ui_WiFi_Connect, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WiFi_Connect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFiProvisioningButton = lv_btn_create(ui_Settings);
    lv_obj_set_width(ui_WiFiProvisioningButton, 182);
    lv_obj_set_height(ui_WiFiProvisioningButton, 31);
    lv_obj_set_x(ui_WiFiProvisioningButton, -46);
    lv_obj_set_y(ui_WiFiProvisioningButton, -68);
    lv_obj_set_align(ui_WiFiProvisioningButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WiFiProvisioningButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WiFiProvisioningButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WiFi_Provisioning = lv_label_create(ui_WiFiProvisioningButton);
    lv_obj_set_width(ui_WiFi_Provisioning, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WiFi_Provisioning, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WiFi_Provisioning, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WiFi_Provisioning, "WiFi Provision");
    lv_obj_set_style_text_color(ui_WiFi_Provisioning, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WiFi_Provisioning, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider3 = lv_slider_create(ui_Settings);
    lv_obj_set_width(ui_Slider3, 161);
    lv_obj_set_height(ui_Slider3, 10);
    lv_obj_set_x(ui_Slider3, -43);
    lv_obj_set_y(ui_Slider3, 12);
    lv_obj_set_align(ui_Slider3, LV_ALIGN_CENTER);


    ui_Slider4 = lv_slider_create(ui_Settings);
    lv_obj_set_width(ui_Slider4, 157);
    lv_obj_set_height(ui_Slider4, 10);
    lv_obj_set_x(ui_Slider4, -44);
    lv_obj_set_y(ui_Slider4, 35);
    lv_obj_set_align(ui_Slider4, LV_ALIGN_CENTER);


    lv_obj_add_event_cb(ui_WiFiProvisioningButton, ui_event_WiFiProvisioningButton, LV_EVENT_ALL, NULL);

}
